jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Download Plugins with Maven
      run: mvn -B antrun:run --file pom.xml
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B source:jar javadoc:jar package --file pom.xml
    - continue-on-error: true
      name: Run Fess
      run: bash src/test/resources/before_script.sh
    - continue-on-error: true
      name: Run Integration Test
      run: bash src/test/resources/run.sh
    timeout-minutes: 15
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
